name: SpotyPoty
description: "Your new music pal"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  http: ^0.13.5
  firebase_database: ^11.3.5
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0
  flutter_dotenv: ^5.0.2
  provider: ^6.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.15

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
